# Generated by Django 5.1.3 on 2025-02-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_review_text_review_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='feedback',
        ),
        migrations.AddField(
            model_name='review',
            name='number',
            field=models.IntegerField(default=9999999999),
        ),
        migrations.AddField(
            model_name='review',
            name='sessions',
            field=models.CharField(blank=True, choices=[('swimming', 'Swimming'), ('biking', 'biking'), ('racing', 'Racing'), ('meeting', 'Meeting')], max_length=50, null=True),
        ),
    ]
