# Generated by Django 5.1.3 on 2025-02-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_feedback_review_number_review_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='allergies',
            field=models.CharField(choices=[('swimming', 'Swimming'), ('biking', 'biking'), ('racing', 'Racing'), ('meeting', 'Meeting')], default='def', max_length=50),
            preserve_default=False,
        ),
    ]
