# Generated by Django 5.1.3 on 2025-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_sessions_alter_review_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sessions',
            field=models.CharField(choices=[('swimming', 'Swimming'), ('biking', 'biking'), ('racing', 'Racing'), ('meeting', 'Meeting')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
