# Generated by Django 5.1.3 on 2025-02-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sessions',
        ),
    ]
